# Dependencies
markdown:         redcarpet
highlighter:      pygments


excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            Barcelona Digital Art
tagline:          1st simultaneous digital art show in Barcelona 
description:      "The 1st exhibition of digital art in Barcelona is presented as a simultaneous exhibition in spaces and buildings of the city. The show was created with the aim of offering to the public the possibility of discovering and experimenting with digital art in environments, a priori, outside the traditional art exhibition circuit. Leisure, culture and heritage will merge to offer an unprecedented experience in Barcelona about digital art."
url:              http://www.digitalartbarcelona.com

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

paginate:         8
paginate_path:    "blog/page:num"

# Custom vars
version:          1.0.0

full-shop:
  repo:           http://www.inpocketart.com/botiga/

twitter-sentence: "| Enjoy #BarcelonaDigitalArt, #BDA"

organitza:
  artinpocket:
    description:  Artinpocket - organitzadors de barcelona digital art
    logo: "artinpocket-organitzadors-barcelona-digital-art-footer.jpg"
  convent-sant-agusti:
    description:  Convent de Sant Agustí - organitzadors de barcelona digital art
    logo: "convent-sant-agusti-organitzadors-barcelona-digital-art-footer.jpg"

patrocina:
  blanz:
    description:  BlanZ - patrocinadors de barcelona digital art
    logo: "blanz-organitzadors-barcelona-digital-art-footer.jpg"
  idodi:
    description:  IDODI - patrocinadors de barcelona digital art
    logo: "idodi-organitzadors-barcelona-digital-art-footer.jpg"
  invysible:
    description:  invysible - patrocinadors de barcelona digital art
    logo: "invysible-organitzadors-barcelona-digital-art-footer.jpg"

colabora:
  tona:
    description:  Tona Codina - col·laboradors de barcelona digital art
    logo: "tona-codina-organitzadors-barcelona-digital-art-footer.jpg"
  moobeat:
    description:  Moobeat - col·laboradors de barcelona digital art
    logo: "moobeat-organitzadors-barcelona-digital-art-footer.jpg"
  oxygen:
    description:  Oxygen - col·laboradors de barcelona digital art
    logo: "oxygen-organitzadors-barcelona-digital-art-footer.jpg"
    url:  http://www.oxygen.cat/
  catalunya-empren:
    description:  Catalunya Emprèn - col·laboradors de barcelona digital art
    logo: "catalunya-empren-organitzadors-barcelona-digital-art-footer.jpg"

participa:
  ryans:
    description: Ryans Irish Pub - participants de barcelona digital art
    logo: ryans-pub-footer-digital-art-barcelona.jpg
  espanya:
    description: Hotel Espanya Rambles - participants de barcelona digital art
    logo: hotel-espanya-footer-digital-art-barcelona.jpg
  alaire:
    description: Alaire Rambles Terrace - participants de barcelona digital art
    logo: alaire-ramblas-terrace-footer-digital-art-barcelona.jpg
  roommate:
    description: Room Mate - participants de barcelona digital art
    logo: room-mate-footer-digital-art-barcelona.jpg

assets: 
  baseurl: /public/

# Prose
prose:
  rooturl: ''
  siteurl: 'http://www.digitalartbarcelona.com/'
  media: 'public/img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ""

