# Site settings
title: "Digital Art Barcelona"
email: info@digitalartbarcelona.com
description: "The 1st exhibition of digital art in Barcelona is presented as a simultaneous exhibition in spaces and buildings of the city. The show was created with the aim of offering to the public the possibility of discovering and experimenting with digital art in environments, a priori, outside the traditional art exhibition circuit. Leisure, culture and heritage will merge to offer an unprecedented experience in Barcelona about digital art."
baseurl: ""
url: "http://www.digitalartbarcelona.com"
twitter_username: artinpocket
github_username:  freecates

# Build settings
markdown: kramdown
permalink: pretty

# Custom vars
icon:		/assets/images/logo-artinpocket-digitalartbarcelona.png
favicon:	/assets/images/favicon.ico