# Dependencies
markdown:         redcarpet
highlighter:      pygments


excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

sass:
 style: compressed

# Setup
title:            MAD Barcelona
tagline:          II Simultaneous Digital Art Show 
description:      "The 2nd exhibition of digital art in Barcelona is presented as a simultaneous exhibition in spaces and buildings of the city. The show was created with the aim of offering to the public the possibility of discovering and experimenting with digital art in environments, a priori, outside the traditional art exhibition circuit. Leisure, culture and heritage will merge to offer an unprecedented experience in Barcelona about digital art."
url:              https://www.digitalartbarcelona.com
twitter_username: freecates
github_username:  freecates
twitter:          Artinpocket

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

endDate: '2015-06-21T23:59:00+02:00'

paginate:         8
paginate_path:    "blog/page:num"

# Custom vars
version:          1.2.0

full-shop:
  repo:           http://www.artinpocket.cat/tienda/

twitter-sentence: "| Enjoy #digitalartbcn, #MADbcn"

organitza:
  artinpocket:
    description:  Artinpocket - organitzadors de barcelona digital art
    logo: "artinpocket-organitzadors-barcelona-digital-art-footer.jpg"
    id: 1
  convent-sant-agusti:
    description:  Convent de Sant Agustí - organitzadors de barcelona digital art
    logo: "convent-sant-agusti-organitzadors-barcelona-digital-art-footer.jpg"
    id: 2

patrocina:
  blanz:
    description:  BlanZ - patrocinadors de barcelona digital art
    logo: "blanz-organitzadors-barcelona-digital-art-footer.jpg"
    id: 3
  canon:
    description:  canon - patrocinadors de barcelona digital art
    logo: "canon-organitzadors-barcelona-digital-art-footer.jpg"
    id: 4
  tram:
    description:  TRAM - patrocinadors de barcelona digital art
    logo: "tram-organitzadors-barcelona-digital-art-footer.jpg"
    id: 5

colabora:
  sercotel:
    description: "SERCOTEL Hotels - col·laboradors de barcelona digital art"
    logo: "sercotel-organitzadors-barcelona-digital-art-footer.jpg"
  gencat:
    description: "Generalitat de Catalunya, Departament de Cultura - col·laboradors de barcelona digital art"
    logo: "generalitat-de-catalunya-organitzadors-barcelona-digital-art-footer.jpg"
  deliverum:
    description: Deliverum - col·laboradors de barcelona digital art
    logo: "deliverum-organitzadors-barcelona-digital-art-footer.jpg"
  tona:
    description:  Tona Codina - col·laboradors de barcelona digital art
    logo: "tona-codina-organitzadors-barcelona-digital-art-footer.jpg"
  arteaunclick:
    description:  Arte a un click - col·laboradors de barcelona digital art
    logo: "arte-a-un-click-organitzadors-barcelona-digital-art-footer.jpg"
  oxygen:
    description:  Oxygen - col·laboradors de barcelona digital art
    logo: "oxygen-organitzadors-barcelona-digital-art-footer.jpg"
    url:  "http://www.oxygen.cat/"

participa:
  convent-sant-agusti:
    description:  Convent de Sant Agustí - organitzadors de barcelona digital art
    logo: "convent-sant-agusti-organitzadors-barcelona-digital-art-footer.jpg"
  nauart:
    description: "NAUART Espacio de creación - participants de barcelona digital art"
    logo: nauart-organitzadors-barcelona-digital-art-footer.jpg
  amister:
    description: "SERCOTEL Amister - participants de barcelona digital art"
    logo: amister-organitzadors-barcelona-digital-art-footer.jpg
  toc:
    description: "TOC Hostel & Suites - participants de barcelona digital art"
    logo: toc-organitzadors-barcelona-digital-art-footer.jpg
  espanya:
    description: Hotel Espanya Rambles - participants de barcelona digital art
    logo: hotel-espanya-footer-digital-art-barcelona.jpg
  alaire:
    description: Alaire Rambles Terrace - participants de barcelona digital art
    logo: alaire-ramblas-terrace-footer-digital-art-barcelona.jpg
  roommate:
    description: Room Mate - participants de barcelona digital art
    logo: room-mate-footer-digital-art-barcelona.jpg
  gorilla:
    description: gorilla - participants de barcelona digital art
    logo: gorilla-organitzadors-barcelona-digital-art-footer.jpg
  balmes:
    description: Restaurant Balmes Rosselló - participants de barcelona digital art
    logo: restarurant-balmes-rossello-organitzadors-barcelona-digital-art-footer.jpg

assets: 
  baseurl: /public/

# Prose
prose:
  rooturl: ''
  siteurl: 'https://www.digitalartbarcelona.com/'
  media: 'public/img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ""

